import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "@arco-design/web-vue/dist/arco.css";
import { arcoPlugin } from "@/plugins";
const app = createApp(App);
arcoPlugin(app);
app.use(router);
app.use(store);
app.mount("#app");
